services:

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yaml"
    volumes:
      - ./ngrok.yaml:/etc/ngrok.yaml
    network_mode: 'host'
      
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  django:
    container_name: django
    build: 
      context: ./securechat
    volumes:
      - ./securechat:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=127.0.0.1,localhost,<INSERT_YOUR_NGROK_DOMAIN_NAME>
      - SECRET_KEY=<INSERT_YOUR_SECRET_KEY>
      - SLACK_API_TOKEN=<INSERT_YOUR_SLACK_API_USER_TOKEN>

    depends_on:
      - redis
