# Generated by Django 5.0.6 on 2024-06-13 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry', models.CharField(max_length=512, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataLeak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('catching_regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.regex')),
            ],
        ),
    ]
